vim.g.python3_host_prog = "/usr/local/bin/python3"

require "core.plugins"
require "core.options"
require "core.keymaps"
require "core.autocommands"
require "core.colorscheme"
require "core.cmp"
require "core.telescope"
require "core.treesitter"
require "core.autopairs"
require "core.comment"
require "core.gitsigns"
require "core.nvim-tree"
require "core.nnn"
require "core.bufferline"
require "core.lualine"
require "core.toggleterm"
require "core.project"
require "core.impatient"
require "core.illuminate"
require "core.indentline"
require "core.alpha"
require "core.lsp"
require "core.dap"
require "core.neorg"

require "user"
